version: '3'

services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://dpg-co5cqqgl6cac73de0jg0-a.frankfurt-postgres.render.com/activeplanet

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgrass
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=password
