version: '3'

services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://dpg-crca1vi3esus739brtig-a.frankfurt-postgres.render.com/fitsync_jx4r

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgrass
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=password
