spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgrass
    username:
    password:
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}

verification:
  url: "http://localhost:4200/verify/"
resetPassword:
  url: "http://localhost:4200/reset-password/"

logging:
  level:
    org.springframework.security.messaging.web.socket: DEBUG
    org.springframework.web.socket.server: DEBUG
