spring:
  datasource:
    url: jdbc:postgresql://dpg-crca1vi3esus739brtig-a.frankfurt-postgres.render.com/fitsync_jx4r
    username: danielbernhardt
    password: RbBGKRkXqtA4WvpGpqpEps35Ebeu0TXv
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}

verification:
  url: "http://localhost:4200/verify/"
resetPassword:
  url: "http://localhost:4200/reset-password/"
DECODE_SECRET_KEY:
  value: "dDRCUU1kSzI3WX5uQ3MoRDQpYWVUVDVJoeisraFBuJng="

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.postgresql: DEBUG
