spring:
  datasource:
    url: jdbc:postgresql://dpg-co5cqqgl6cac73de0jg0-a.frankfurt-postgres.render.com/activeplanet
    username: danielbernhardt
    password: FEntx9ZSXZIXORZrTnID8rLSwFHWDim3
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}

verification:
  url: "http://localhost:4200/verify/"