spring:
  datasource:
    url: jdbc:postgresql://dpg-csofm3ij1k6c73bfsna0-a.frankfurt-postgres.render.com/active_planet_q6i0
    username: active_planet_q6i0_user
    password: 9p9mQd5K2IApC1OHyc8u6AUDJkiPZ8NG
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  flyway:
    baseline-on-migrate: true
  cache:
    type: simple
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.gymplanet@gmail.com
    password: yvcf pjnn gswm oczf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  stripe:
    secret-key: sk_test_51NeitKEQK2sno4KoC18hdz4HdpV5nJz7vcbsS976zif7aK3su1CF84QEMv8GQesajzvsoN4QuphmcQysyXoJauVO004L8xptok
    webhook-key: whsec_83ce88d9036b4e9fab2a70df4ca82eb540b865a780af607442b26876feb34ddc
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
server:
  port: ${PORT:10000}




verification:
  url: https://active-planet.netlify.app/verify/
resetPassword:
  url: http://active-planet.netlify.app/reset-password/
DECODE_SECRET_KEY:
  value: "dDRCUU1kSzI3WX5uQ3MoRDQpYWVUVDVJoeisraFBuJng="